### ISSUE TITLE
elm-search in the address bar

### ISSUE THREAD

**Issue by tomek-he-him** [klaftertief/elm-search#11]
Hey Jonas!

First of all, elm-search is downright awesome! Such a useful tool!

I love it so much that I want a super quick shortcut to it – a search engine in the browser address bar. So using chrome://settings/searchEngines, I added a new search engine mapping to the string `http://klaftertief.github.io/elm-search/?q=%s`.

There is a problem with this though. When I use this search engine to look for “List String -> String”, here’s the URL it sends me to: “http://klaftertief.github.io/elm-search/?q=List+String+-%3E+String”. Click the link to see what elm-search tries to look for in that case: `List+String+->+String`. No results. Not ideal.

As far as I’ve heard, passing `+` as a space is not only a super widespread convention, but it also sits in some RFC standard.

I’d love this to get sorted, so elm-search is even easier to use! 💙

**Comment by klaftertief** [comment]
Thanks for the input and I'm glad you like it.

A single ` `is now en- and decoded as`+`, so that should fix you issue.

It's a breaking change with regard that searches for `http://klaftertief.github.io/elm-search/?q=++` now won't find the `++` operator/function, you have to use the encoded version `http://klaftertief.github.io/elm-search/?q=%2B%2B`. But this should only matter when you write the URL by hand.

**Comment by klaftertief** [comment]
You might need to hard reload the page as there is no cache invalidation help set up yet.
And, as mentioned at the conference, the indexing takes a while, so it might be quicker having the search page open and directly write the queries there.
